<?php
/**
 * Bloomreach Connector extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Bloomreach Proprietary License
 * that is bundled with this package in the file LICENSE.txt.
 *
 * @category       Bloomreach
 * @package        Connector
 * @copyright      Copyright (c) 2021-current Bloomreach Inc.
 */
?>
<?php
use Magento\Framework\Escaper;

/* @var $block \Bloomreach\Connector\Block\System\Config\Form\Field\CtaButtonAbstract */
/** @var Escaper $escaper */
?>

<a class="action-default scalable"
   target="_blank"
   href="<?= $escaper->escapeUrl($block->getButtonUrl()) ?>"
   id="<?= $escaper->escapeHtmlAttr($block->getButtonId()) ?>">
    <span><?= $escaper->escapeHtml($block->getButtonLabel()) ?></span>
</a>
<?php
if (!empty($block->getAdditionalText())) {
    echo '<div class="clearfix"><p>&nbsp;</p>' . $block->getAdditionalText() . '</div>';
}
?>


