<?php
/**
 * Copyright © Bloomreach, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block Bloomreach\Connector\Block\Widget\Recommendation */
$randonId = rand();
?>
<?php if ($block->isWidgetVisible()): ?>
    <div class="widget recommendation pathways-recommendation-widget" data-bind="scope: 'brsmRecommendationWidget<?= $randonId ?>'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "brsmRecommendationWidget<?= $randonId ?>": {
                            "component": "Bloomreach_Connector/js/view/recommendation",
                            "template" : "Bloomreach_Connector/widget/recommendation",
                            "widgetConfig": <?= $block->getWidgetJsonConfig() ?>
                        }
                    }
                }
            }
        }
    </script>
<?php endif; ?>
